paypay/paypayopa-sdk-python

- paypayopa/resources/code.py
- paypayopa/resources/payment.py
> Update get payment details url

- paypayopa/constants/url.py
- paypayopa/resources/__init__.py
- paypayopa/resources/pending.py
> Add pending payments resource to SDK

- README.md
> Add Pending payments to document

- README.md
> added CII badge url

- README.md
> add bettercode

- paypayopa/client.py
> Sonarcloud fixes

- .github/workflows/python-publish.yml
> Remove use of set-env in GitHub actions

- paypayopa/client.py
> Update url param change

- paypayopa/client.py
> Request unknown key api_id fix

- paypayopa/client.py
> Hotfix for request options issue

- paypayopa/resources/payment.py
> Remove UIAD from refund fix

- .pylintrc
- paypayopa/resources/payment.py
> Add paymentId check and pylint ruleset

- .github/workflows/build-ci.yml
> Buildciupdate

- paypayopa/resources/account.py
> Add CREATE_QR_SESSION api_id to account linking

- .github/workflows/build-ci.yml
- paypayopa/constants/api_list.py
- paypayopa/constants/url.py
- paypayopa/resources/pending.py
- tests/test_refund_request_order.py
> Update pending payment refund API

- paypayopa/constants/api_list.py
- paypayopa/resources/cashback.py
> Update API_ID to backend mapping

- paypayopa/client.py
> Set alogorithm to decode jwt

- README.md
> Add documentation for unlink API call

- .github/workflows/build-ci.yml
- setup.py
> Remove UUID from python 2 backport as a dependecy

- paypayopa/resources/pending.py
> Fix validation typo on pending payment refund

- paypayopa/client.py
- paypayopa/constants/url.py
> Add perf mode implementation

- paypayopa/resources/payment.py
- paypayopa/resources/pending.py
> Proper requested at seconds is passed to refund apis

- paypayopa/resources/pending.py
- tests/test_cancel_request_order.py
Updated the refund rul as wrong url was used in the refund details api earlier.
> Used valid url for refund details
